export interface Theme {
  name: string;
  properties: any;
}

export const light: Theme = {
  name: 'light',
  properties: {
    '--foreground-default': '#F4F6F9',
    '--foreground-table': '#FFFFFF',
    '--font-table': '#00529B',
    '--font-table-content': '#00529B',
    '--color-main-font': '#0C1D55',
    '--color-default-font': '#00529b',
    '--color-href-font': '#5aaef3',
    '--foreground-widgets': '#FFFFFF',
    '--tittleLeads': '#0c1d55',
    '--subtitleWidget': '#00529b',
    '--numberWidget': '#5aaef3',
    '--boxShadowWidget': '0px 5px 10px 1px gainsboro',
    '--gross-profit': '#FFFFFF',
    '--graph-Appointments': '#FFFFFF',
    '--custom-select': '#dbe3f1',
    '--font-filtros': '#00529b',
    '--task-description': '#00529b',
    '--table-responsive': '#dee2e6',
    '--label-center': '#0C1D55',
    '--alert-warning': '#ffffff',
    '--bg-item-dashboard': '#dee2e6',
    '--fondo-dia': '#ffffff',
    '--border-left-calendar': '#dee2e6',
    '--fondo-dia-actual': '#ffffff',
    '--fondo-dia-tittle': '#ffffff',
    '--font-dia-title': '#1f316b',
    '--border-left-color': '#dee2e6 ',
    '--pag-bg-num': '#DBE3F1',
    '--pag-bg-arrows': '#00529B',
    '--pag-bg-selected': '#DBE3F1',
    '--pag-bg-hover': '#0068c5',
    '--pag-color-num': '#5AAEF3',
    '--pag-color-selected': '#00529b',
    '--pag-color-arrows': '#5AAEF3',
    '--pag-color-hover': '#eae5eb',
    '--right-menu-bg': '#f4f6f9',
    '--right-menu-color': '#0C1D55',
    '--color-h3': '#0C1D55',
    '--input-color': '#95a5e2',
    '--input-bg': '#f8fafe',
    '--input-border': '#d8edff',
    '--text-a': '#d8edff',
    '--panels-lead': '#dbe3f1',
    '--circle-step': '#0c1d55',
    '--bg-group-workflow': '#FFFFFF',
    '--icons-select': 'url(/assets/img/AOSP/view_icon_col.svg)',
    '--icons-down': '#00529b',
    '--border-Calendar-color': '#eae5eb',
    '--font-day-color': 'red',
    '--events-calendar-day': '#cccccc5e ',
    '--fond-hover': '#f4f6f9',
  }
};

export const dark: Theme = {
  name: 'dark',
  properties: {
    '--foreground-default': '#001347',
    '--foreground-table': '#0c1d55',
    '--font-table': '#FFFFFF',
    '--font-table-content': '#cac5cb',
    '--color-main-font': '#eae5eb',
    '--color-default-font': '#eae5eb',
    '--color-href-font': '#5aaef3',
    '--foreground-widgets': '#0c1d55',
    '--tittleLeads': '#FFFFFF',
    '--subtitleWidget': '#FFFFFF',
    '--numberWidget': '#5aaef3',
    '--boxShadowWidget': '0px 5px 10px 1px #00182b',
    '--gross-profit': '#0c1d55',
    '--graph-Appointments': '#0c1d55',
    '--custom-select': '#1F316B',
    '--font-filtros': '#ffffff',
    '--task-description': '#ffffff',
    '--table-responsive': 'transparent',
    '--label-center': '#ffffff',
    '--alert-warning': '#0C1D55',
    '--bg-item-dashboard': 'transparent',
    '--fondo-dia': '#0c1d55',
    '--border-left-calendar': '#041325',
    '--fondo-dia-actual': '#0C1D55',
    '--fondo-dia-tittle': '#0C1D55',
    '--font-dia-title': '#ffffff',
    '--border-left-color': '#041325',
    '--pag-bg-num': '#1F316B',
    '--pag-bg-arrows': '#1F316B',
    '--pag-bg-selected': '#1F316B',
    '--pag-bg-hover': '#0068c5',
    '--pag-color-num': '#427EBE',
    '--pag-color-selected': '#FFFFFF',
    '--pag-color-arrows': '#427EBE',
    '--pag-color-hover': '#eae5eb',
    '--right-menu-bg': '#0c1d55',
    '--right-menu-color': '#eae5eb',
    '--color-h3': '#eae5eb',
    '--input-color': '#5a6aa5',
    '--input-bg': '#1f316b',
    '--input-border': '#1f316b',
    '--text-a': '#d8edff',
    '--panels-lead': '#0c1d55',
    '--circle-step': '#adc9df',
    '--bg-group-workflow': '#0c1d55',
    '--icons-select': 'url(/assets/img/AOSP/view_icon.svg)',
    '--icons-down': '#ffffff',
    '--border-Calendar-color': '#041325',
    '--font-day-color': '#0068c5',
    '--events-calendar-day': '#3c4e89',
    '--fond-hover': '#001347',
  }
};
